require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 100
  Exclude:
    - 'config/initializers/**/*'

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/concepts/**/*'

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 8

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

AllCops:
  Exclude:
    - 'bin/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'lib/tasks/*'
    - 'log/**/*'
    - 'tmp/**/*'
